<?php
include('functions.php');
make_connection();
if(isset($_POST['subscribe_submit']))
{
    insert_subscribe($_POST['email']);
    header("Location:index.php");
}
if(isset($_POST['contact_submit']))
{
    insert_contact($_POST['name'],$_POST['email'],$_POST['subject'],$_POST['message']);
    header("Location:index.php");
}
?>